name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Lint-Code:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Running Dependencies Install..."
          npm ci
      - name: Run Linting
        run: |
          echo "Running Linting..."
          npm run lint
        env:
          CI: true
  Unit-Test-Code:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: |
          echo "Running Unit Tests..."
          npm run test
        env:
          CI: true
  E2E-Test-Code:
    name: E2E Tests (Cypress)
    runs-on: ubuntu-latest
    steps:
      - name: Build Next.js app
        run: |
          echo "Running build..."
          npm run build
      - name: Start Next.js app
        run: |
          echo "Running start command..."
          npm run start
      - name: Run E2E Tests (Cypress)
        run: |
          echo "Running E2E Tests (Cypress)..."
          npm run cypress:headless
        env:
          CI: true
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
